EDA on the Netflix DataSet

Beginner

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Loading the data and taking a first look(basic inspection)

In [2]:
netflix=pd.read_csv("../data/netflix_data.csv")

In [3]:
netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [4]:
netflix.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [5]:
netflix.shape

(8807, 12)

In [6]:
netflix.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [7]:
#Datatype of every column
netflix.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [8]:
#Null Values In Each Column
netflix.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [9]:
#Percentage of director missing
netflix.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

In [10]:
#Percentage of director missing
missing_val=netflix['director'].isnull().sum()
total_values=len(netflix['director'])
director_missing_percentage=(missing_val/total_values)*100

In [11]:
print(director_missing_percentage)

29.908027705234474

Calculates the percentage of missing values in the 'director' column by mean method

In [12]:
missing_percentage=netflix['director'].isnull().mean()*100

In [13]:
print(missing_percentage)

29.908027705234474

What percentage of `cast` is missing?

In [14]:
cast_missing_percentage=netflix['cast'].isnull().mean()*100
print(cast_missing_percentage)

9.367548540933349

What percentage of `country` is missing?

In [15]:
netflix.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

In [16]:
country_missing_percentage=netflix['country'].isnull().mean()*100
print(country_missing_percentage)

9.435676166685592

 How many rows have a missing `date_added`, `rating`, or `duration`?

In [17]:
netflix[['date_added','rating','duration']].isnull().any(axis=1).sum()

np.int64(17)

Are there any duplicate `show_id` values?

In [18]:
netflix['show_id'].duplicated().sum()#Means each show id is unique and one id is not repeated anywhere

np.int64(0)

Are there any fully duplicate rows?

In [19]:
netflix.duplicated().sum()

np.int64(0)

Are there any duplicate `title` values?

In [20]:
netflix['title'].duplicated().sum()

np.int64(0)

What is the count of each `type` value (Movie vs. TV Show)?

In [21]:
netflix['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

What is the minimum and maximum `release_year`?

In [22]:
min_year=netflix['release_year'].min()
max_year=netflix['release_year'].max()
print(min_year)
print(max_year)

1925
2021

 Print every unique value in the `rating` column.

In [23]:
netflix['rating'].nunique()

17

In [24]:
print(netflix['rating'].unique())

['PG-13' 'TV-MA' 'PG' 'TV-14' 'TV-PG' 'TV-Y' 'TV-Y7' 'R' 'TV-G' 'G'
 'NC-17' '74 min' '84 min' '66 min' 'NR' nan 'TV-Y7-FV' 'UR']

Looking at that list — do any values look out of place for a content-rating column (hint: do any look like a duration instead)?

 Print the full rows where `rating` is one of those odd values — what do you notice about their `duration` column?

In [25]:
netflix[netflix['rating'].isin(['74 min','84 min','66 min'])]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

What is the count of missing `duration` values, split by `type`?

In [26]:
movies=netflix['type']=="Movie"
tv_shows=netflix['type']=="TV Show"

In [27]:
print(netflix[movies]['duration'].isnull().sum())
print(netflix[tv_shows]['duration'].isnull().sum())

3
0

Correct method to solve this(GROUP BY)

In [28]:
netflix['duration'].isna().groupby(netflix['type']).sum()

type
Movie      3
TV Show    0
Name: duration, dtype: int64

Print a few raw `duration` values for Movies vs. a few for TV Shows — are they even in the same format?

In [29]:
netflix[['type','duration']].groupby('type').head()

       type   duration
0     Movie     90 min
1   TV Show  2 Seasons
2   TV Show   1 Season
3   TV Show   1 Season
4   TV Show  2 Seasons
5   TV Show   1 Season
6     Movie     91 min
7     Movie    125 min
9     Movie    104 min
12    Movie    127 min

Print a few raw `date_added` values — is this stored as text or as an actual date?

In [30]:
netflix[['date_added']].head()

           date_added
0  September 25, 2021
1  September 24, 2021
2  September 24, 2021
3  September 24, 2021
4  September 24, 2021

Print a few raw `country` values — does any single row contain more than one country?

In [31]:
netflix[['country']].head(20)

                                              country
0                                       United States
1                                        South Africa
2                                                 NaN
3                                                 NaN
4                                               India
5                                                 NaN
6                                                 NaN
7   United States, Ghana, Burkina Faso, United Kin...
8                                      United Kingdom
9                                       United States
10                                                NaN
11                                                NaN
12                            Germany, Czech Republic
13                                                NaN
14                                                NaN
15                                      United States
16                                                NaN
17                                             Mexico
18                                                NaN
19                                                NaN

How many unique raw `country` strings exist, before any splitting?

In [32]:
netflix['country'].nunique()

748

Print a few raw `cast` values — is this a single name, or several names packed into one string?

In [33]:
netflix[['cast']]

                                                   cast
0                                                   NaN
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
3                                                   NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...
...                                                 ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
8803                                                NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...

[8807 rows x 1 columns]

Print a few raw `listed_in` values — same comma-separated pattern?

In [34]:
netflix.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [35]:
netflix[['listed_in']].head()

                                           listed_in
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

#🟡 INTERMEDIATE — Cleaning, Parsing & Aggregation

 Fix the 3 misplaced `rating` rows from Beginner — move the duration value into `duration` and set `rating` to a proper missing value. What's your justification for not just dropping these 3 rows?

In [40]:
netflix[netflix['rating'].isin(['74 min','84 min','66 min'])]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [62]:
mask=netflix['rating'].isin(['74 min','84 min','66 min'])

In [64]:
netflix.loc[mask,'rating']

5541    74 min
5794    84 min
5813    66 min
Name: rating, dtype: object

In [63]:
netflix.loc[mask,'duration']

5541    NaN
5794    NaN
5813    NaN
Name: duration, dtype: object

In [65]:
netflix.loc[mask,'duration']=netflix.loc[mask,'rating']

In [66]:
netflix.loc[mask,'rating']=np.nan

In [67]:
netflix[mask]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,NaN,74 min,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,NaN,84 min,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,NaN,66 min,Movies,The comic puts his trademark hilarious/thought...